# Generated by Django 5.2 on 2025-04-29 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_alter_student_semester'),
        ('studentPanel', '0002_student_profile_picture_student_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpaper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.student'),
        ),
        migrations.AlterField(
            model_name='feereceipt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
