# Generated by Django 5.2 on 2025-04-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPanel', '0003_alter_backpaper_student_alter_feereceipt_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackPaper',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
