# Generated by Django 5.2 on 2025-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPanel', '0004_delete_backpaper_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
