# Generated by Django 5.2 on 2025-04-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.subject')),
            ],
        ),
    ]
