# Generated by Django 5.2 on 2025-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
