# Generated by Django 5.2 on 2025-04-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='background.jpg', upload_to='profile_pics/'),
        ),
    ]
