# Generated by Django 5.2 on 2025-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0008_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='full_name_branch',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='full_name_institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
