# Generated by Django 5.2 on 2025-04-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_examdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamDetail',
        ),
    ]
