# Generated by Django 5.2 on 2025-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_examdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
