# Generated by Django 5.2 on 2025-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_student_blood_group_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='student.png', upload_to='profile_pics/'),
        ),
    ]
