# Generated by Django 5.2 on 2025-05-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0018_alter_admin_options_alter_admin_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
