# Generated by Django 5.2 on 2025-05-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_adminuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
